# Generated by Django 4.2.1 on 2023-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Firstname', models.CharField(max_length=200)),
                ('user_lastName', models.CharField(max_length=200)),
            ],
        ),
    ]
