# Generated by Django 4.2.1 on 2023-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0002_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrentsfield',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
