# Generated by Django 4.2.1 on 2023-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0002_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(default='field_name', max_length=255),
        ),
    ]
