# Generated by Django 4.2.1 on 2023-05-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0003_remove_renter_has_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterRatesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('id_renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportista.renter')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportista.sportistauser')),
            ],
        ),
        migrations.AddField(
            model_name='renter',
            name='rates_user',
            field=models.ManyToManyField(blank=True, through='sportista.RenterRatesUser', to='sportista.sportistauser'),
        ),
    ]
