# Generated by Django 4.2.1 on 2023-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0003_teamrentsfield_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrentsfield',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
