# Generated by Django 4.2.1 on 2023-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0004_alter_teamrentsfield_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
