# Generated by Django 4.2.1 on 2023-06-11 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0005_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
